# Caddyfile
adamk.hu {
    reverse_proxy 192.168.50.200:80
    encode gzip
    
    # Security headers
    header {
        X-Frame-Options SAMEORIGIN
        X-Content-Type-Options nosniff
        X-XSS-Protection "1; mode=block"
    }
}