services:
  adamk-gallery:
    build: .
    container_name: adamk-gallery
    restart: unless-stopped
    ports:
      - "50000:80"  # Change port as needed
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./logs:/var/log/nginx